/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwtbam.view.components;

import javax.swing.JOptionPane;
import wwtbam.controller.IItemObserver;
import wwtbam.view.Observable;

/**
 *
 * @author Visitor
 */
public class HomePanel extends javax.swing.JPanel implements Observable{

    /**
     * Creates new form HomePanel
     */
    IItemObserver observer;
    public HomePanel() {
        
        initComponents();
    }
    public void showInstructions() {
        JOptionPane.showMessageDialog(this, new InstructionPanel(),"Instructions",JOptionPane.PLAIN_MESSAGE,null);
    }

    public void showAbout() {
        JOptionPane.showMessageDialog(this, new AboutPanel(), "About Us", JOptionPane.PLAIN_MESSAGE, null);
    }
    
 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Startbtn = new javax.swing.JButton();
        Helpbtn = new javax.swing.JButton();
        Creditsbtn = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();

        Startbtn.setText("START");
        Startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartbtnActionPerformed(evt);
            }
        });

        Helpbtn.setText("Help");
        Helpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpbtnActionPerformed(evt);
            }
        });

        Creditsbtn.setText("CREDITS");
        Creditsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditsbtnActionPerformed(evt);
            }
        });

        Exitbtn.setText("EXIT");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 289, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Startbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Creditsbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Helpbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Exitbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Startbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Helpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Creditsbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreditsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditsbtnActionPerformed
       showAbout();
    }//GEN-LAST:event_CreditsbtnActionPerformed

    private void HelpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpbtnActionPerformed
       showInstructions();
    }//GEN-LAST:event_HelpbtnActionPerformed

    private void StartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartbtnActionPerformed
        observer.start();
        observer.toQuestionPanel();
    }//GEN-LAST:event_StartbtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
       observer.exitGame();
    }//GEN-LAST:event_ExitbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Creditsbtn;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Helpbtn;
    private javax.swing.JButton Startbtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addObserver(IItemObserver observer) {
        this.observer = observer;
    }
}
