/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wwtbam.view;

import javax.swing.JButton;
import wwtbam.model.IChoice;

/**
 *
 * @author lipat
 */
public class JButtonChoice extends JButton {

    /**
     * Creates new form JButtonItem
     */
    
    IChoice choice;
    public JButtonChoice() {
        initComponents();
    }

    public void setChoice(IChoice choice) {
        this.choice = choice;
    }

    public IChoice getChoice() {
        return choice;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
